name = "vladimir"
uuid = "c6a228e0-bb52-4238-a26d-109ac73abb74"
authors = ["AssertionBit <113050317+AssertionBit@users.noreply.github.com>"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
